21 09 handle longer qvalues
socketry/http-accept pull request #16
Opened 2021-09-12 23:12 UTC by Khaled9447

## Description

The current implementation expects `qvalues` with at most 3 decimal places (e.g. q=0.001) which of course is correct in general. However, looks like some browsers send `qvalues` with longer decimal places; the below example was encountered by one of our products in the company I work at:
**"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6, ag;q=0.0001"**

This string raises an exception **"Could not parse entire string!"** which we had to rescue from and provide a fallback locale.
The main issue can be noticed at the end of the string with `q=0.0001` which have 4 decimal places.

### Types of Changes
- Bug fix.

### Testing
- [ ] I tested my changes locally.

2021-09-12 23:54 UTC, ioquatix commented
@Khaled9447 can you please remove b918b6b thanks :)

Is there some maximum number of decimal places we should accept? What do the RFCs state?

2021-09-12 23:55 UTC, ioquatix commented
It seems like this is invalid:

> immediately followed by a value between 0 and 1 included, with up to three decimal digits

What browser is sending this?

2021-09-14 09:22 UTC, Khaled9447 commented
@ioquatix  sorry for the delay :bow: 
I checked on w3 and seems like they recommended 3 digits only.. this is weird, I really don't know if there is a limit :thinking: 
This is the information from the sending browser:

```
"Sec-Ch-Ua": "\"Microsoft Edge\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"",
"Sec-Ch-Ua-Mobile": "?0",
"Sec-Ch-Ua-Platform": "\"Windows\"",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 Edg/93.0.961.38/PTI16Rbj-46",
"Accept-Language": "de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6, ag;q=0.0001"
```

2021-09-14 10:49 UTC, ioquatix commented
I think we can accept it, but it goes against the RFC. As long as we don't generate it... we can be generous in what we accept. But maybe let's limit it up to 6 decimal places?

The reason for a limit would be to prevent parsing or representation bugs. If you know there is only 3 d.p. you can use integer representation (maybe suitable for low end hardware which doesn't have floating point support).

2021-09-14 11:18 UTC, Khaled9447 commented
@ioquatix  totally agree, a limit of 6 d.p would be nice!
I think qvalues with more than 3 d.p is very rare anyway so we should be on the safe side now :grin: 
I pushed the change :+1:

2021-09-14 11:41 UTC, ioquatix commented
Can you please add specs.

2021-09-15 09:31 UTC, Khaled9447 commented
@ioquatix added the sepc :+1: 
Please check the tests naming and let me know if you prefer a different naming :D

2021-09-15 10:38 UTC, ioquatix commented
It looks good to me.

Please avoid the unnecessary changes to whitespace, and please use hard tabs for indentation.

2021-09-15 14:34 UTC, Khaled9447 commented
@ioquatix ahhh sorry my VSC settings :sweat_smile: 
Done :+1:

2021-09-15 20:08 UTC, ioquatix commented on spec/http/languages_spec.rb
> +  it "should accept quality factors up to 6 decimal places" do
Indentation here :)

2021-09-15 20:09 UTC, ioquatix requested changes
LGTM just minor formatting issues then we can merge.

2021-09-15 20:09 UTC, ioquatix commented on spec/http/languages_spec.rb
> +  it "should not accept quality factors with more than 6 decimal places" do
Indentation here.

2021-09-18 13:02 UTC, Khaled9447 commented
@ioquatix done :bow:

2021-09-18 21:29 UTC, merged